# -*- coding: utf-8 -*-
config = {
    'btc' :  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7000",
        'currency_name': 'Bitcoin (BTC)',
        'symbol': "฿",
        'code': 'BTC',
        'network': "mainnet",
    },
    'ltc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7001",
        'currency_name': 'Litecoin (LTC)',
        'symbol': "Ł",
        'code': 'LTC',
        'network': "mainnet",
    },
    'nmc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7002",
        'currency_name': 'Namecoin (NMC)',
        'symbol': "ℕ",
        'code': 'NMC',
        'network': "mainnet",
    },
    'ppc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'currency_name': 'PPcoin (PPC)',
        'symbol': "Ᵽ",
        'code': 'PPC',
        'network': "mainnet",
    },
    'ftc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'currency_name': 'Feathercoin (FTC)',
        'symbol': "ƒ",
        'code': 'FTC',
        'network': "mainnet",
    },
}