# -*- coding: utf-8 -*-
config = [
    {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7000",
        'name': 'Bitcoin (BTC)',
        'symbol': "฿",
        'currency': 'BTC',
    },
    {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7001",
        'name': 'Litecoin (LTC)',
        'symbol': "Ł",
        'currency': 'LTC',
    },
    {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7002",
        'name': 'Namecoin (NMC)',
        'symbol': "ℕ",
        'currency': 'NMC',
    },
    {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'name': 'PPcoin (PPC)',
        'symbol': "Ᵽ",
        'currency': 'PPC',
    },
    {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'name': 'Feathercoin (FTC)',
        'symbol': "ƒ",
        'currency': 'FTC',
    },
]