# -*- coding: UTF8 -*-
config = {
    'btc' :  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7000",
        'currency_name': 'BitCoin (BTC)',
        'symbol': "B⃦",
        'code': 'BTC',
        'network': "mainnet",
    },
    'ltc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7001",
        'currency_name': 'LiteCoin (LTC)',
        'symbol': "Ł",
        'code': 'LTC',
        'network': "mainnet",
    },
    'nmc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7002",
        'currency_name': 'NameCoin (NMC)',
        'symbol': "ℕ",
        'code': 'NMC',
        'network': "mainnet",
    },
    'ppc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'currency_name': 'PPCoin (PPC)',
        'symbol': "Ᵽ",
        'code': 'PPC',
        'network': "mainnet",
    },
    'ftc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "7003",
        'currency_name': 'FeatherCoin (FTC)',
        'symbol': "ƒ",
        'code': 'FTC',
        'network': "mainnet",
    },
}