# -*- coding: UTF8 -*-
config = [
    {
        'id': 1,
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7000",
        'name': 'Bitcoin (BTC)',
        'currency': 'btc',
        'symbol': "฿",
    },
    {
        'id': 2,
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "localhost",
        'rpcport': "9000",
        'name': 'Lottery wallet',
        'currency': 'btc',
        'symbol': "฿",
    },
    {
        'id': 3,
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7001",
        'name': 'Litecoin (LTC)',
        'currency': 'ltc',
        'symbol': "Ł",
    },
    {
        'id': 4,
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7002",
        'name': 'Namecoin (NMC)',
        'currency': 'nmc',
        'symbol': "ℕ",
    },
    {
        'id': 5,
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7003",
        'name': 'PPcoin (PPC)',
        'currency': 'ppc',
        'symbol': "Ᵽ",
    },
]


'''
config = {
    'btc' :  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7000",
        'currency_name': 'Bitcoin (BTC)',
        'symbol': "฿",
        'code': 'BTC',
        'network': "testnet",
    },
    'ltc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7001",
        'currency_name': 'Litecoin (LTC)',
        'symbol': "Ł",
        'code': 'LTC',
        'network': "testnet",
    },
    'nmc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7002",
        'currency_name': 'Namecoin (NMC)',
        'symbol': "ℕ",
        'code': 'NMC',
        'network': "testnet",
    },
    'ppc':  {
        'rpcusername': "testuser",
        'rpcpassword': "testnet",
        'rpchost': "tiny",
        'rpcport': "7003",
        'currency_name': 'PPcoin (PPC)',
        'symbol': "Ᵽ",
        'code': 'PPC',
        'network': "testnet",
    },
}
'''